- OG_data:
    bckup: 1561723022_sdp_l0.full_1284.full_pol_1024ch_3C274_150MHz_64_chn_32s.ms

- Duplicates:
    mslist: auto1,auto2,auto3

- UV_range:
    uvrange: nill,\>150m,\>150m

- Masking:
    mask_list: nill,nill,nill

- Wsclean_range:
    min_range:  nill,150,nill

- BDSM:
    bdsf_par: nill,nill,nill

- Imaging:
    robustness: -2.0,-1.0,-0.5
    auto_threshold: 15,10,5
    automatic_mask_size: 5,5,5
