- OG_data:
    bckup: 1561723022_sdp_l0.full_1284.full_pol_split_1024ch_3C274_64_chn_32s.ms

- Duplicates:
    mslist: auto1,auto2,auto3

- UV_range:
    uvrange: nill,nill,nill

- Masking:
    mask_list: nill,nill,nill

- Wsclean_range:
    min_range:  nill,nill,nill

- BDSM:
    bdsf_par: nill,nill,nill

- Imaging:
    robustness: -2.0,-2.0,-2.0
    auto_threshold: 3,3,3
    automatic_mask_size: 5,5,5
    multiscale_clean: True,True,True
    multiscale_scales: 10;20;30,10;20;30,10;20;30

- EMAIL:
    address: 13371062@tuks.co.za

#----------------------------------------------------------------------------
#----------------------------------------------------------------------------
## The purpose of this experience is to test the effectiveness of:
#
## On the conclusion of this job I expect to comment on:
#
## The importance of leaving the state of the parameter as
# active/disabled
## For the following reason:
#
#----------------------------------------------------------------------------
